spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: Vfrcbv11
    driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        ddl-auto: create-drop
server:
  port: 8082